#参考使用pnpm:https://github.com/marketplace/actions/setup-node-and-pnpm
name: Deploy documentation

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: setup node and pnpm
              uses: dafnik/setup-node-pnpm@v1
              with:
                  pnpm: 7
                  node: 16
              # cwd: "."
              # install: false
              # install-ignore-scripts: false

            - name: Install dependencies
              run: pnpm install

            - name: Generate typedoc documentation
              run: pnpm run doc

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: docs
                  token: ${{ secrets.GITHUB_TOKEN }}
